### ISSUE TITLE
error on startup

### ISSUE THREAD

**Issue by Maaajaaa** [Moldoteck/EmojiMixing#3]
Hi, I've tried to setup emojimixing on my vps, however I ran into an issue when trying to run it:

```[TypeScript] 
[Node] internal/modules/cjs/loader.js:818
[Node]   throw err;
[Node]   ^
[Node] 
[Node] Error: Cannot find module '/root/EmojiMixing/dist/app.js'
[Node]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
[Node]     at Function.Module._load (internal/modules/cjs/loader.js:667:27)
[Node]     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
[Node]     at internal/main/run_main_module.js:17:47 {
[Node]   code: 'MODULE_NOT_FOUND',
[Node]   requireStack: []
[Node] }
[Node] [nodemon] app crashed - waiting for file changes before starting...
```

which I don't quite understand (as I also know next to nothing about node), but that file, the whole dist folder even, does not exist.

**Comment by Moldoteck** [comment]
Hi. Probably I haven't described the setup&launch steps properly. Will look into them tomorrow, thx
